version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/search_gov_crawler"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        patterns:
          - "python-json-logger"
          - "scrapy*"
          - "spidermon*"
          - "apscheduler"
          - "elasticsearch"
          - "redis"
          - "newspaper4k*"
          - "cchardet"
          - "python-dotenv"
          - "pypdf"
          - "langdetect"
          - "python-dateutil"
      testing-linting-and-scripts:
        patterns:
          - "click"
          - "freezegun"
          - "pylint"
          - "pytest*"
          - "rich"
    ignore:
      # see requirements.txt for more details
      - dependency-name: "lxml-html-clean"
      - dependency-name: "typing-extensions"
      - dependency-name: "redis"
        versions: [ ">=6" ]
      - dependency-name: "elasticsearch"
        versions: [ ">=9" ]
