version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/search_gov_crawler"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        patterns:
          - "python-json-logger"
          - "scrapy*"
          - "spidermon*"
          - "apscheduler"
          - "elasticsearch"
          - "redis"
          - "newspaper4k*"
          - "cchardet"
          - "python-dotenv"
          - "pypdf"
          - "langdetect"
          - "python-dateutil"
      testing-and-linting:
        patterns:
          - "freezegun"
          - "pylint"
          - "pytest*"
    ignore:
      - dependency-name: "lxml-html-clean"
      - dependency-name: "typing-extensions"
