version: '2'
checks:
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-lines:
    enabled: false
  method-count:
    enabled: false
  method-complexity:
    enabled: false

plugins:
  duplication:
    enabled: true
  fixme:
    enabled: true
  sonar-python:
    enabled: true
    exclude_patterns:
    - "**/settings.py"
  pep8:
    enabled: true

exclude_patterns:
- "**/*.htm"
- "**/*.html"
- "**/*.xml"
- "**/*.yml"
- "**/.*"
- "**/__pycache__/"