version: 0.0
os: linux
# files:
#   - source: .
#     destination: /home/ec2-user/spider
permissions:
  - object: cicd-scripts/app_install.sh
    owner: search
    mode: 755
    type:
      - file
  - object: cicd-scripts/app_start.sh
    owner: search
    mode: 755
    type:
      - file
  - object: cicd-scripts/app_stop.sh
    owner: search
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: cicd-scripts/app_install.sh
      timeout: 300
      runas: search
  ApplicationStart:
    - location: cicd-scripts/app_start.sh
      timeout: 300
      runas: search
  ApplicationStop:
    - location: cicd-scripts/app_stop.sh
      timeout: 300
      runas: search
