# Install plugins for OpenSearch
FROM docker.io/opensearchproject/opensearch:3.1

RUN opensearch-plugin install analysis-kuromoji
RUN opensearch-plugin install analysis-icu
RUN opensearch-plugin install analysis-smartcn
