services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./es_index_setup.sh:/es_index_setup.sh
      - ./es_index_settings.json:/es_index_settings.json
    post_start:
      - command: bash -c "source /es_index_setup.sh"
        user: root
        privileged: true
        environment:
          - SEARCHELASTIC_INDEX=searchgov-spider
          - ES_HOSTS=http://localhost:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:7.17.20
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN="true"
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge
