FROM python:3.12-slim
WORKDIR /usr/src/searchgov-spider
SHELL ["/bin/bash", "-c"]

# Install system dependencies
RUN apt-get update \
    && apt-get install -y \
    lzma liblzma-dev libbz2-dev acl build-essential checkinstall libreadline-dev libncursesw5-dev \
    libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev zlib1g-dev libffi-dev openssl

# Copy project files and set up virtual environment
COPY . .
RUN touch .env
RUN python3.12 -m venv venv
RUN source venv/bin/activate

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install --with-deps
RUN playwright install chrome --force
RUN python search_gov_crawler/search_engines/install_nltk.py
