services:
  elasticsearch:
    build:
      context: ./
      dockerfile: DockerFile.elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
    healthcheck:
      test: curl -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - spider

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5601:5601
    expose:
      - 5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - spider

  opensearch:
    build:
      context: ./
      dockerfile: DockerFile.opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9300:9200
    expose:
      - 9300
    healthcheck:
      test: curl -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - spider

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - 5602:5601
    expose:
      - 5602
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - spider
  redis:
    image: redis:6.2.6
    container_name: redis
    healthcheck:
      test: redis-cli ping >/dev/null || exit 1
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 6379:6379
    networks:
      - spider

  spider:
    &spider
    build:
      context: .
      dockerfile: DockerFile.dev
    env_file:
      - .env.development
    environment:
      PYTHONPATH: /usr/src/searchgov-spider
    depends_on:
      redis:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    network_mode: host
    profiles:
      - spider

  scheduler:
    <<: *spider
    command: python search_gov_crawler/scrapy_scheduler.py

  sitemap:
    <<: *spider
    command: python search_gov_crawler/run_sitemap_monitor.py

volumes:
  elasticsearch_data:
  opensearch_data:

networks:
  spider:
    driver: bridge
