services:
  elasticsearch:
    build:
      context: ./
      dockerfile: DockerFile.elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
    healthcheck:
      test: curl -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - spider

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    expose:
      - 5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - spider

  opensearch:
    build:
      context: ./
      dockerfile: DockerFile.opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9300:9200
    expose:
      - 9300
    healthcheck:
      test: curl -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - spider

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.0
    depends_on:
      - opensearch
    ports:
      - 5602:5601
    expose:
      - 5602
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - spider
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - spider

volumes:
  elasticsearch_data:
  opensearch_data:


networks:
  spider:
    driver: bridge
