version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "./search_gov_crawler/requirements.txt" }}
      - run: echo PYTHONPATH = $PYTHONPATH
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r ./search_gov_crawler/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "./search_gov_crawler/requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest -k 'not TestSpiderFullCrawl'

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
