name: GSA-TTS Scanning Service
on: [pull_request]
jobs:
  lint:
    uses: GSA-TTS/scanning-service/.github/workflows/dependency-lint.yml@main
    with:
      fail-on-error: false # advisory mode; set true to block PRs
  scan:
    uses: GSA-TTS/scanning-service/.github/workflows/secret-scan.yml@main
    with:
      fail-on-error: false # advisory mode; set true to block PRs
